object DependencyVersions {
    const val activity = "1.5.0"
    const val androidAnnotation = "1.4.0"
    const val androidGradlePlugin = "1.7.0"
    const val androidNavigation = "2.5.0"
    const val androidxArch = "2.1.0"
    const val androidxCore = "1.8.0"
    const val appcompat = "1.4.2"
    const val compose = "1.2.0"
    const val composeActivity = "1.5.0"
    const val constraintLayout = "2.1.4"
    const val dagger = "2.41"
    const val dependencyGuardPlugin = "0.3.0"
    const val fragment = "1.5.0"
    const val gradleVersionsFilterPlugin = "0.1.16"
    const val junit = "4.12"
    const val kotlin = "1.7.0"
    const val kotlinCoroutines = "1.6.1"
    const val kotlinSerialization = "1.3.2"
    const val leakCanary = "2.7"
    const val lifecycle = "2.5.0"
    const val recyclerview = "1.2.1"
    const val slf4android = "0.1.6"
    const val slf4j = "1.7.26"
}
